### PR TITLE
Add angular momentum operator and materialization for spherical harmonics

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
The infinite block banded matrices are giving me error messages I haven't been able to understand when creating an infinite skew tridiagonal matrix with 0s on main diag and subdiagonal like `[0 | 0 1 | 0 | 0 1 0 2 | 0 | 0 1 0 2 0 3 | 0 | ...]` (the lines respecting the block structure) and super its negative. @dlfivefifty

### CODE REVIEW

**Comment by dlfivefifty** [comment]
MWE and error message please

**Comment by MikaelSlevinsky** [comment]
```julia
julia> using HarmonicOrthogonalPolynomials, StaticArrays, Test, InfiniteArrays, LinearAlgebra, BlockArrays, ClassicalOrthogonalPolynomials, QuasiArrays

julia> import Base: oneto

julia> k = mortar(Base.OneTo.(0:2:∞))
ℵ₀-blocked ℵ₀-element BlockVector{Int64, LazyArrays.BroadcastVector{Base.OneTo{Int64}, Type{Base.OneTo}, Tuple{InfiniteArrays.InfStepRange{Int64, Int64}}}, Tuple{BlockedUnitRange{ArrayLayouts.RangeCumsum{Int64, InfiniteArrays.InfStepRange{Int64, Int64}}}}}:
 1
 2
 ─
 1
 2
 3
 4
 ─
 1
 2
 3
 4
 5
 6
 ─
 1
 2
 3
 4
 5
 6
 7
 8
 ─
 1
 2
 3
 4
 ⋮

julia> m = T.(iseven.(k) .* (k .÷ 2))
Float64.((iseven.(ℵ₀-blocked ℵ₀-element BlockVector{Int64, LazyArrays.BroadcastVector{Base.OneTo{Int64}, Type{Base.OneTo}, Tuple{InfiniteArrays.InfStepRange{Int64, Int64}}}, Tuple{BlockedUnitRange{ArrayLayouts.RangeCumsum{Int64, InfiniteArrays.InfStepRange{Int64, Int64}}}}}) with indices 1:1:+∞) .* (div.(ℵ₀-blocked ℵ₀-element BlockVector{Int64, LazyArrays.BroadcastVector{Base.OneTo{Int64}, Type{Base.OneTo}, Tuple{InfiniteArrays.InfStepRange{Int64, Int64}}}, Tuple{BlockedUnitRange{ArrayLayouts.RangeCumsum{Int64, InfiniteArrays.InfStepRange{Int64, Int64}}}}}, Int64) with indices 1:1:+∞) with indices 1:1:+∞) with indices 1:1:+∞:
 0.0
 1.0
 ───
 0.0
 1.0
 0.0
 2.0
 ───
 0.0
 1.0
 0.0
 2.0
 0.0
 3.0
 ───
 0.0
 1.0
 0.0
 2.0
 0.0
 3.0
 0.0
 4.0
 ───
 0.0
 1.0
 0.0
 2.0
 ⋮

julia> 
```

I want the `m` vector to be the sub diagonal entries of a `BlockBandedMatrix`. `m` only describes the subdiagonal entries in the main diagonal blocks (of size 1x1, 3x3, 5x5,... implying none in the first block), so there are zeros associated with the adjacent blocks that are not defined by the vector `m`.

**Comment by MikaelSlevinsky** [comment]
Ok so I guess it makes sense to have the `AngularMomentum` as an operator in this repository next to the Laplacian. It's mergeable, can add the `RealSphericalHarmonic` case when the infinite skew-tridiagonal matrix can be constructed.

**Comment by dlfivefifty** [comment]
Note technically adding a new exported name counts as a "breaking" change, but since this repository is not widely used its fine.

**Pull request merged**
